//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSNPSharp.MSNWS.MSNStorageService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StorageServiceBinding", Namespace="http://www.msn.com/webservices/storage/2008")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentStream[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relationship[]))]
    public partial class StorageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AffinityCacheHeader affinityCacheHeaderValueField;
        
        private StorageApplicationHeader storageApplicationHeaderValueField;
        
        private StorageUserHeader storageUserHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShareItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRelationshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRelationshipsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StorageService() {
            this.Url = "https://storage.msn.com/storageservice/SchematizedStore.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AffinityCacheHeader AffinityCacheHeaderValue {
            get {
                return this.affinityCacheHeaderValueField;
            }
            set {
                this.affinityCacheHeaderValueField = value;
            }
        }
        
        public StorageApplicationHeader StorageApplicationHeaderValue {
            get {
                return this.storageApplicationHeaderValueField;
            }
            set {
                this.storageApplicationHeaderValueField = value;
            }
        }
        
        public StorageUserHeader StorageUserHeaderValue {
            get {
                return this.storageUserHeaderValueField;
            }
            set {
                this.storageUserHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProfileCompletedEventHandler GetProfileCompleted;
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        public event FindDocumentsCompletedEventHandler FindDocumentsCompleted;
        
        /// <remarks/>
        public event CreateProfileCompletedEventHandler CreateProfileCompleted;
        
        /// <remarks/>
        public event ShareItemCompletedEventHandler ShareItemCompleted;
        
        /// <remarks/>
        public event CreateDocumentCompletedEventHandler CreateDocumentCompleted;
        
        /// <remarks/>
        public event UpdateDocumentCompletedEventHandler UpdateDocumentCompleted;
        
        /// <remarks/>
        public event CreateRelationshipsCompletedEventHandler CreateRelationshipsCompleted;
        
        /// <remarks/>
        public event DeleteRelationshipsCompletedEventHandler DeleteRelationshipsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/GetProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProfileResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public GetProfileResponse GetProfile([System.Xml.Serialization.XmlElementAttribute("GetProfile", Namespace="http://www.msn.com/webservices/storage/2008")] GetProfileRequestType GetProfile1) {
            object[] results = this.Invoke("GetProfile", new object[] {
                        GetProfile1});
            return ((GetProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequestType GetProfile1) {
            this.GetProfileAsync(GetProfile1, null);
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequestType GetProfile1, object userState) {
            if ((this.GetProfileOperationCompleted == null)) {
                this.GetProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileOperationCompleted);
            }
            this.InvokeAsync("GetProfile", new object[] {
                        GetProfile1}, this.GetProfileOperationCompleted, userState);
        }
        
        private void OnGetProfileOperationCompleted(object arg) {
            if ((this.GetProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileCompleted(this, new GetProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/UpdateProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateProfileResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public object UpdateProfile([System.Xml.Serialization.XmlElementAttribute("UpdateProfile", Namespace="http://www.msn.com/webservices/storage/2008")] UpdateProfileRequestType UpdateProfile1) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        UpdateProfile1});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(UpdateProfileRequestType UpdateProfile1) {
            this.UpdateProfileAsync(UpdateProfile1, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(UpdateProfileRequestType UpdateProfile1, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        UpdateProfile1}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/FindDocuments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FindDocumentsResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public FindDocumentsResultType FindDocuments([System.Xml.Serialization.XmlElementAttribute("FindDocuments", Namespace="http://www.msn.com/webservices/storage/2008")] FindDocumentsRequestType FindDocuments1) {
            object[] results = this.Invoke("FindDocuments", new object[] {
                        FindDocuments1});
            return ((FindDocumentsResultType)(results[0]));
        }
        
        /// <remarks/>
        public void FindDocumentsAsync(FindDocumentsRequestType FindDocuments1) {
            this.FindDocumentsAsync(FindDocuments1, null);
        }
        
        /// <remarks/>
        public void FindDocumentsAsync(FindDocumentsRequestType FindDocuments1, object userState) {
            if ((this.FindDocumentsOperationCompleted == null)) {
                this.FindDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindDocumentsOperationCompleted);
            }
            this.InvokeAsync("FindDocuments", new object[] {
                        FindDocuments1}, this.FindDocumentsOperationCompleted, userState);
        }
        
        private void OnFindDocumentsOperationCompleted(object arg) {
            if ((this.FindDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindDocumentsCompleted(this, new FindDocumentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/CreateProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateProfileResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public CreateProfileResponse CreateProfile([System.Xml.Serialization.XmlElementAttribute("CreateProfile", Namespace="http://www.msn.com/webservices/storage/2008")] CreateProfileRequestType CreateProfile1) {
            object[] results = this.Invoke("CreateProfile", new object[] {
                        CreateProfile1});
            return ((CreateProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProfileAsync(CreateProfileRequestType CreateProfile1) {
            this.CreateProfileAsync(CreateProfile1, null);
        }
        
        /// <remarks/>
        public void CreateProfileAsync(CreateProfileRequestType CreateProfile1, object userState) {
            if ((this.CreateProfileOperationCompleted == null)) {
                this.CreateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProfileOperationCompleted);
            }
            this.InvokeAsync("CreateProfile", new object[] {
                        CreateProfile1}, this.CreateProfileOperationCompleted, userState);
        }
        
        private void OnCreateProfileOperationCompleted(object arg) {
            if ((this.CreateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProfileCompleted(this, new CreateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/ShareItem", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ShareItemResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public ShareItemResponseType ShareItem([System.Xml.Serialization.XmlElementAttribute("ShareItem", Namespace="http://www.msn.com/webservices/storage/2008")] ShareItemRequestType ShareItem1) {
            object[] results = this.Invoke("ShareItem", new object[] {
                        ShareItem1});
            return ((ShareItemResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ShareItemAsync(ShareItemRequestType ShareItem1) {
            this.ShareItemAsync(ShareItem1, null);
        }
        
        /// <remarks/>
        public void ShareItemAsync(ShareItemRequestType ShareItem1, object userState) {
            if ((this.ShareItemOperationCompleted == null)) {
                this.ShareItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShareItemOperationCompleted);
            }
            this.InvokeAsync("ShareItem", new object[] {
                        ShareItem1}, this.ShareItemOperationCompleted, userState);
        }
        
        private void OnShareItemOperationCompleted(object arg) {
            if ((this.ShareItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShareItemCompleted(this, new ShareItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/CreateDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateDocumentResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public CreateDocumentResponseType CreateDocument([System.Xml.Serialization.XmlElementAttribute("CreateDocument", Namespace="http://www.msn.com/webservices/storage/2008")] CreateDocumentRequestType CreateDocument1) {
            object[] results = this.Invoke("CreateDocument", new object[] {
                        CreateDocument1});
            return ((CreateDocumentResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDocumentAsync(CreateDocumentRequestType CreateDocument1) {
            this.CreateDocumentAsync(CreateDocument1, null);
        }
        
        /// <remarks/>
        public void CreateDocumentAsync(CreateDocumentRequestType CreateDocument1, object userState) {
            if ((this.CreateDocumentOperationCompleted == null)) {
                this.CreateDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDocumentOperationCompleted);
            }
            this.InvokeAsync("CreateDocument", new object[] {
                        CreateDocument1}, this.CreateDocumentOperationCompleted, userState);
        }
        
        private void OnCreateDocumentOperationCompleted(object arg) {
            if ((this.CreateDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDocumentCompleted(this, new CreateDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/UpdateDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateDocumentResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public object UpdateDocument([System.Xml.Serialization.XmlElementAttribute("UpdateDocument", Namespace="http://www.msn.com/webservices/storage/2008")] UpdateDocumentRequestType UpdateDocument1) {
            object[] results = this.Invoke("UpdateDocument", new object[] {
                        UpdateDocument1});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDocumentAsync(UpdateDocumentRequestType UpdateDocument1) {
            this.UpdateDocumentAsync(UpdateDocument1, null);
        }
        
        /// <remarks/>
        public void UpdateDocumentAsync(UpdateDocumentRequestType UpdateDocument1, object userState) {
            if ((this.UpdateDocumentOperationCompleted == null)) {
                this.UpdateDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDocumentOperationCompleted);
            }
            this.InvokeAsync("UpdateDocument", new object[] {
                        UpdateDocument1}, this.UpdateDocumentOperationCompleted, userState);
        }
        
        private void OnUpdateDocumentOperationCompleted(object arg) {
            if ((this.UpdateDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDocumentCompleted(this, new UpdateDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/CreateRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateRelationshipsResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public object CreateRelationships([System.Xml.Serialization.XmlElementAttribute("CreateRelationships", Namespace="http://www.msn.com/webservices/storage/2008")] CreateRelationshipsRequestType CreateRelationships1) {
            object[] results = this.Invoke("CreateRelationships", new object[] {
                        CreateRelationships1});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRelationshipsAsync(CreateRelationshipsRequestType CreateRelationships1) {
            this.CreateRelationshipsAsync(CreateRelationships1, null);
        }
        
        /// <remarks/>
        public void CreateRelationshipsAsync(CreateRelationshipsRequestType CreateRelationships1, object userState) {
            if ((this.CreateRelationshipsOperationCompleted == null)) {
                this.CreateRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRelationshipsOperationCompleted);
            }
            this.InvokeAsync("CreateRelationships", new object[] {
                        CreateRelationships1}, this.CreateRelationshipsOperationCompleted, userState);
        }
        
        private void OnCreateRelationshipsOperationCompleted(object arg) {
            if ((this.CreateRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRelationshipsCompleted(this, new CreateRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageApplicationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AffinityCacheHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("StorageUserHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.msn.com/webservices/storage/2008/DeleteRelationships", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteRelationshipsResponse", Namespace="http://www.msn.com/webservices/storage/2008")]
        public object DeleteRelationships([System.Xml.Serialization.XmlElementAttribute("DeleteRelationships", Namespace="http://www.msn.com/webservices/storage/2008")] DeleteRelationshipsRequestType DeleteRelationships1) {
            object[] results = this.Invoke("DeleteRelationships", new object[] {
                        DeleteRelationships1});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRelationshipsAsync(DeleteRelationshipsRequestType DeleteRelationships1) {
            this.DeleteRelationshipsAsync(DeleteRelationships1, null);
        }
        
        /// <remarks/>
        public void DeleteRelationshipsAsync(DeleteRelationshipsRequestType DeleteRelationships1, object userState) {
            if ((this.DeleteRelationshipsOperationCompleted == null)) {
                this.DeleteRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRelationshipsOperationCompleted);
            }
            this.InvokeAsync("DeleteRelationships", new object[] {
                        DeleteRelationships1}, this.DeleteRelationshipsOperationCompleted, userState);
        }
        
        private void OnDeleteRelationshipsOperationCompleted(object arg) {
            if ((this.DeleteRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRelationshipsCompleted(this, new DeleteRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/2008", IsNullable=false)]
    public partial class StorageApplicationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string applicationIDField;
        
        private string scenarioField;
        
        public StorageApplicationHeader() {
            this.applicationIDField = "Messenger Client 8.5";
            this.scenarioField = "Initial";
        }
        
        /// <remarks/>
        public string ApplicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        public string Scenario {
            get {
                return this.scenarioField;
            }
            set {
                this.scenarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class DeleteRelationshipsRequestType {
        
        private Handle sourceHandleField;
        
        private Handle[] targetHandlesField;
        
        /// <remarks/>
        public Handle sourceHandle {
            get {
                return this.sourceHandleField;
            }
            set {
                this.sourceHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ObjectHandle", IsNullable=false)]
        public Handle[] targetHandles {
            get {
                return this.targetHandlesField;
            }
            set {
                this.targetHandlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class Handle {
        
        private Alias aliasField;
        
        private string relationshipNameField;
        
        private string resourceIDField;
        
        /// <remarks/>
        public Alias Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string RelationshipName {
            get {
                return this.relationshipNameField;
            }
            set {
                this.relationshipNameField = value;
            }
        }
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class Alias {
        
        private string nameField;
        
        private string nameSpaceField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string NameSpace {
            get {
                return this.nameSpaceField;
            }
            set {
                this.nameSpaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateRelationshipsRequestType {
        
        private Relationship[] relationshipsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Relationship[] relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class Relationship {
        
        private string sourceIDField;
        
        private string sourceTypeField;
        
        private string targetIDField;
        
        private string targetTypeField;
        
        private string relationshipNameField;
        
        /// <remarks/>
        public string SourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string TargetID {
            get {
                return this.targetIDField;
            }
            set {
                this.targetIDField = value;
            }
        }
        
        /// <remarks/>
        public string TargetType {
            get {
                return this.targetTypeField;
            }
            set {
                this.targetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RelationshipName {
            get {
                return this.relationshipNameField;
            }
            set {
                this.relationshipNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateDocumentResponseType {
        
        private string createDocumentResultField;
        
        /// <remarks/>
        public string CreateDocumentResult {
            get {
                return this.createDocumentResultField;
            }
            set {
                this.createDocumentResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateDocumentRequestType {
        
        private Handle parentHandleField;
        
        private documentBaseType documentField;
        
        private string relationshipNameField;
        
        /// <remarks/>
        public Handle parentHandle {
            get {
                return this.parentHandleField;
            }
            set {
                this.parentHandleField = value;
            }
        }
        
        /// <remarks/>
        public documentBaseType document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public string relationshipName {
            get {
                return this.relationshipNameField;
            }
            set {
                this.relationshipNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Photo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class documentBaseType {
        
        private string resourceIDField;
        
        private string nameField;
        
        private string itemTypeField;
        
        private string dateModifiedField;
        
        private DocumentStream[] documentStreamsField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DocumentStream[] DocumentStreams {
            get {
                return this.documentStreamsField;
            }
            set {
                this.documentStreamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhotoStream))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class DocumentStream {
        
        private string documentStreamNameField;
        
        private string mimeTypeField;
        
        private byte[] dataField;
        
        private int dataSizeField;
        
        private string preAuthURLField;
        
        private string preAuthURLPartnerField;
        
        private string documentStreamTypeField;
        
        private string writeModeField;
        
        private int streamVersionField;
        
        private byte[] sHA1HashField;
        
        private bool genieField;
        
        /// <remarks/>
        public string DocumentStreamName {
            get {
                return this.documentStreamNameField;
            }
            set {
                this.documentStreamNameField = value;
            }
        }
        
        /// <remarks/>
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int DataSize {
            get {
                return this.dataSizeField;
            }
            set {
                this.dataSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string PreAuthURL {
            get {
                return this.preAuthURLField;
            }
            set {
                this.preAuthURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string PreAuthURLPartner {
            get {
                return this.preAuthURLPartnerField;
            }
            set {
                this.preAuthURLPartnerField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentStreamType {
            get {
                return this.documentStreamTypeField;
            }
            set {
                this.documentStreamTypeField = value;
            }
        }
        
        /// <remarks/>
        public string WriteMode {
            get {
                return this.writeModeField;
            }
            set {
                this.writeModeField = value;
            }
        }
        
        /// <remarks/>
        public int StreamVersion {
            get {
                return this.streamVersionField;
            }
            set {
                this.streamVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SHA1Hash {
            get {
                return this.sHA1HashField;
            }
            set {
                this.sHA1HashField = value;
            }
        }
        
        /// <remarks/>
        public bool Genie {
            get {
                return this.genieField;
            }
            set {
                this.genieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class PhotoStream : DocumentStream {
        
        private int sizeXField;
        
        private bool sizeXFieldSpecified;
        
        private int sizeYField;
        
        private bool sizeYFieldSpecified;
        
        /// <remarks/>
        public int SizeX {
            get {
                return this.sizeXField;
            }
            set {
                this.sizeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeXSpecified {
            get {
                return this.sizeXFieldSpecified;
            }
            set {
                this.sizeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SizeY {
            get {
                return this.sizeYField;
            }
            set {
                this.sizeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeYSpecified {
            get {
                return this.sizeYFieldSpecified;
            }
            set {
                this.sizeYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class Photo : documentBaseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class UpdateDocumentRequestType {
        
        private documentBaseType documentField;
        
        /// <remarks/>
        public documentBaseType document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class ShareItemResponseType {
        
        private string shareItemResultField;
        
        /// <remarks/>
        public string ShareItemResult {
            get {
                return this.shareItemResultField;
            }
            set {
                this.shareItemResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class ShareItemRequestType {
        
        private string resourceIDField;
        
        private string displayNameField;
        
        /// <remarks/>
        public string resourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateProfileRequestType {
        
        private CreateProfileRequestTypeProfile profileField;
        
        /// <remarks/>
        public CreateProfileRequestTypeProfile profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateProfileRequestTypeProfile {
        
        private ExpressionProfile expressionProfileField;
        
        /// <remarks/>
        public ExpressionProfile ExpressionProfile {
            get {
                return this.expressionProfileField;
            }
            set {
                this.expressionProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class ExpressionProfile {
        
        private string freeTextField;
        
        private string displayNameField;
        
        private string personalStatusField;
        
        private int flagsField;
        
        private bool flagsFieldSpecified;
        
        private string roleDefinitionNameField;
        
        /// <remarks/>
        public string FreeText {
            get {
                return this.freeTextField;
            }
            set {
                this.freeTextField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        public int Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagsSpecified {
            get {
                return this.flagsFieldSpecified;
            }
            set {
                this.flagsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string RoleDefinitionName {
            get {
                return this.roleDefinitionNameField;
            }
            set {
                this.roleDefinitionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsResultType {
        
        private FindDocumentsResultTypeDocument documentField;
        
        /// <remarks/>
        public FindDocumentsResultTypeDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsResultTypeDocument {
        
        private string resourceIDField;
        
        private string nameField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsRequestType {
        
        private Handle objectHandleField;
        
        private FindDocumentsRequestTypeDocumentAttributes documentAttributesField;
        
        private FindDocumentsRequestTypeDocumentFilter documentFilterField;
        
        private FindDocumentsRequestTypeDocumentSort documentSortField;
        
        private FindDocumentsRequestTypeFindContext findContextField;
        
        /// <remarks/>
        public Handle objectHandle {
            get {
                return this.objectHandleField;
            }
            set {
                this.objectHandleField = value;
            }
        }
        
        /// <remarks/>
        public FindDocumentsRequestTypeDocumentAttributes documentAttributes {
            get {
                return this.documentAttributesField;
            }
            set {
                this.documentAttributesField = value;
            }
        }
        
        /// <remarks/>
        public FindDocumentsRequestTypeDocumentFilter documentFilter {
            get {
                return this.documentFilterField;
            }
            set {
                this.documentFilterField = value;
            }
        }
        
        /// <remarks/>
        public FindDocumentsRequestTypeDocumentSort documentSort {
            get {
                return this.documentSortField;
            }
            set {
                this.documentSortField = value;
            }
        }
        
        /// <remarks/>
        public FindDocumentsRequestTypeFindContext findContext {
            get {
                return this.findContextField;
            }
            set {
                this.findContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsRequestTypeDocumentAttributes {
        
        private bool resourceIDField;
        
        private bool nameField;
        
        /// <remarks/>
        public bool ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsRequestTypeDocumentFilter {
        
        private string filterAttributesField;
        
        public FindDocumentsRequestTypeDocumentFilter() {
            this.filterAttributesField = "None";
        }
        
        /// <remarks/>
        public string FilterAttributes {
            get {
                return this.filterAttributesField;
            }
            set {
                this.filterAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsRequestTypeDocumentSort {
        
        private string sortByField;
        
        public FindDocumentsRequestTypeDocumentSort() {
            this.sortByField = "DateModified";
        }
        
        /// <remarks/>
        public string SortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class FindDocumentsRequestTypeFindContext {
        
        private string findMethodField;
        
        private int chunkSizeField;
        
        public FindDocumentsRequestTypeFindContext() {
            this.findMethodField = "Default";
        }
        
        /// <remarks/>
        public string FindMethod {
            get {
                return this.findMethodField;
            }
            set {
                this.findMethodField = value;
            }
        }
        
        /// <remarks/>
        public int ChunkSize {
            get {
                return this.chunkSizeField;
            }
            set {
                this.chunkSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class UpdateProfileRequestType {
        
        private UpdateProfileRequestTypeProfile profileField;
        
        private UpdateProfileRequestTypeProfileAttributesToDelete profileAttributesToDeleteField;
        
        /// <remarks/>
        public UpdateProfileRequestTypeProfile profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        public UpdateProfileRequestTypeProfileAttributesToDelete profileAttributesToDelete {
            get {
                return this.profileAttributesToDeleteField;
            }
            set {
                this.profileAttributesToDeleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class UpdateProfileRequestTypeProfile {
        
        private string resourceIDField;
        
        private ExpressionProfile expressionProfileField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public ExpressionProfile ExpressionProfile {
            get {
                return this.expressionProfileField;
            }
            set {
                this.expressionProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class UpdateProfileRequestTypeProfileAttributesToDelete {
        
        private ExpressionProfileAttributesType expressionProfileAttributesField;
        
        /// <remarks/>
        public ExpressionProfileAttributesType ExpressionProfileAttributes {
            get {
                return this.expressionProfileAttributesField;
            }
            set {
                this.expressionProfileAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class ExpressionProfileAttributesType {
        
        private bool resourceIDField;
        
        private bool resourceIDFieldSpecified;
        
        private bool dateModifiedField;
        
        private bool dateModifiedFieldSpecified;
        
        private bool displayNameField;
        
        private bool displayNameFieldSpecified;
        
        private bool displayNameLastModifiedField;
        
        private bool displayNameLastModifiedFieldSpecified;
        
        private bool personalStatusField;
        
        private bool personalStatusFieldSpecified;
        
        private bool personalStatusLastModifiedField;
        
        private bool personalStatusLastModifiedFieldSpecified;
        
        private bool staticUserTilePublicURLField;
        
        private bool staticUserTilePublicURLFieldSpecified;
        
        private bool photoField;
        
        private bool photoFieldSpecified;
        
        private bool attachmentsField;
        
        private bool attachmentsFieldSpecified;
        
        private bool flagField;
        
        private bool flagFieldSpecified;
        
        /// <remarks/>
        public bool ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResourceIDSpecified {
            get {
                return this.resourceIDFieldSpecified;
            }
            set {
                this.resourceIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateModifiedSpecified {
            get {
                return this.dateModifiedFieldSpecified;
            }
            set {
                this.dateModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayNameSpecified {
            get {
                return this.displayNameFieldSpecified;
            }
            set {
                this.displayNameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayNameLastModified {
            get {
                return this.displayNameLastModifiedField;
            }
            set {
                this.displayNameLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayNameLastModifiedSpecified {
            get {
                return this.displayNameLastModifiedFieldSpecified;
            }
            set {
                this.displayNameLastModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonalStatusSpecified {
            get {
                return this.personalStatusFieldSpecified;
            }
            set {
                this.personalStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PersonalStatusLastModified {
            get {
                return this.personalStatusLastModifiedField;
            }
            set {
                this.personalStatusLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonalStatusLastModifiedSpecified {
            get {
                return this.personalStatusLastModifiedFieldSpecified;
            }
            set {
                this.personalStatusLastModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool StaticUserTilePublicURL {
            get {
                return this.staticUserTilePublicURLField;
            }
            set {
                this.staticUserTilePublicURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StaticUserTilePublicURLSpecified {
            get {
                return this.staticUserTilePublicURLFieldSpecified;
            }
            set {
                this.staticUserTilePublicURLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhotoSpecified {
            get {
                return this.photoFieldSpecified;
            }
            set {
                this.photoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttachmentsSpecified {
            get {
                return this.attachmentsFieldSpecified;
            }
            set {
                this.attachmentsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagSpecified {
            get {
                return this.flagFieldSpecified;
            }
            set {
                this.flagFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class GetProfileResultType {
        
        private string resourceIDField;
        
        private string dateModifiedField;
        
        private GetProfileResultTypeExpressionProfile expressionProfileField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public GetProfileResultTypeExpressionProfile ExpressionProfile {
            get {
                return this.expressionProfileField;
            }
            set {
                this.expressionProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class GetProfileResultTypeExpressionProfile {
        
        private string resourceIDField;
        
        private string dateModifiedField;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        private int flagsField;
        
        private documentBaseType photoField;
        
        private documentBaseType[] attachmentsField;
        
        private string personalStatusField;
        
        private string personalStatusLastModifiedField;
        
        private string displayNameField;
        
        private string displayNameLastModifiedField;
        
        private string staticUserTilePublicURLField;
        
        /// <remarks/>
        public string ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Flags {
            get {
                return this.flagsField;
            }
            set {
                this.flagsField = value;
            }
        }
        
        /// <remarks/>
        public documentBaseType Photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Document", IsNullable=false)]
        public documentBaseType[] Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatus {
            get {
                return this.personalStatusField;
            }
            set {
                this.personalStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalStatusLastModified {
            get {
                return this.personalStatusLastModifiedField;
            }
            set {
                this.personalStatusLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayNameLastModified {
            get {
                return this.displayNameLastModifiedField;
            }
            set {
                this.displayNameLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string StaticUserTilePublicURL {
            get {
                return this.staticUserTilePublicURLField;
            }
            set {
                this.staticUserTilePublicURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class profileAttributes {
        
        private bool resourceIDField;
        
        private bool dateModifiedField;
        
        private ExpressionProfileAttributesType expressionProfileAttributesField;
        
        public profileAttributes() {
            this.resourceIDField = true;
            this.dateModifiedField = true;
        }
        
        /// <remarks/>
        public bool ResourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public bool DateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        public ExpressionProfileAttributesType ExpressionProfileAttributes {
            get {
                return this.expressionProfileAttributesField;
            }
            set {
                this.expressionProfileAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class GetProfileRequestType {
        
        private Handle profileHandleField;
        
        private profileAttributes profileAttributesField;
        
        /// <remarks/>
        public Handle profileHandle {
            get {
                return this.profileHandleField;
            }
            set {
                this.profileHandleField = value;
            }
        }
        
        /// <remarks/>
        public profileAttributes profileAttributes {
            get {
                return this.profileAttributesField;
            }
            set {
                this.profileAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/2008", IsNullable=false)]
    public partial class AffinityCacheHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string cacheKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string CacheKey {
            get {
                return this.cacheKeyField;
            }
            set {
                this.cacheKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.msn.com/webservices/storage/2008", IsNullable=false)]
    public partial class StorageUserHeader : System.Web.Services.Protocols.SoapHeader {
        
        private int puidField;
        
        private int cidField;
        
        private string ticketTokenField;
        
        private bool isAdminField;
        
        public StorageUserHeader() {
            this.puidField = 0;
            this.cidField = 0;
            this.isAdminField = false;
        }
        
        /// <remarks/>
        public int Puid {
            get {
                return this.puidField;
            }
            set {
                this.puidField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Cid {
            get {
                return this.cidField;
            }
            set {
                this.cidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string TicketToken {
            get {
                return this.ticketTokenField;
            }
            set {
                this.ticketTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class GetProfileResponse {
        
        private GetProfileResultType getProfileResultField;
        
        /// <remarks/>
        public GetProfileResultType GetProfileResult {
            get {
                return this.getProfileResultField;
            }
            set {
                this.getProfileResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.msn.com/webservices/storage/2008")]
    public partial class CreateProfileResponse {
        
        private string createProfileResultField;
        
        /// <remarks/>
        public string CreateProfileResult {
            get {
                return this.createProfileResultField;
            }
            set {
                this.createProfileResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetProfileCompletedEventHandler(object sender, GetProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProfileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void FindDocumentsCompletedEventHandler(object sender, FindDocumentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindDocumentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindDocumentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FindDocumentsResultType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FindDocumentsResultType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateProfileCompletedEventHandler(object sender, CreateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateProfileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ShareItemCompletedEventHandler(object sender, ShareItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShareItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShareItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShareItemResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShareItemResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateDocumentCompletedEventHandler(object sender, CreateDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDocumentResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDocumentResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateDocumentCompletedEventHandler(object sender, UpdateDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateRelationshipsCompletedEventHandler(object sender, CreateRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteRelationshipsCompletedEventHandler(object sender, DeleteRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591