//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MSNPSharp.MSNWS.MSNRSIService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RSIBinding", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetMetadataResponseType))]
    public partial class RSIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private PassportCookie passportCookieValueField;
        
        private System.Threading.SendOrPostCallback GetMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMessagesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RSIService() {
            this.Url = "https://msnmsgr.escargot.chat/rsi/rsi.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public PassportCookie PassportCookieValue {
            get {
                return this.passportCookieValueField;
            }
            set {
                this.passportCookieValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMetadataCompletedEventHandler GetMetadataCompleted;
        
        /// <remarks/>
        public event GetMessageCompletedEventHandler GetMessageCompleted;
        
        /// <remarks/>
        public event DeleteMessagesCompletedEventHandler DeleteMessagesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PassportCookieValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hotmail.msn.com/ws/2004/09/oim/rsi/GetMetadata", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetMetadataResponse", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
        public object GetMetadata([System.Xml.Serialization.XmlElementAttribute("GetMetadata", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")] GetMetadataRequestType GetMetadata1) {
            object[] results = this.Invoke("GetMetadata", new object[] {
                        GetMetadata1});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void GetMetadataAsync(GetMetadataRequestType GetMetadata1) {
            this.GetMetadataAsync(GetMetadata1, null);
        }
        
        /// <remarks/>
        public void GetMetadataAsync(GetMetadataRequestType GetMetadata1, object userState) {
            if ((this.GetMetadataOperationCompleted == null)) {
                this.GetMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataOperationCompleted);
            }
            this.InvokeAsync("GetMetadata", new object[] {
                        GetMetadata1}, this.GetMetadataOperationCompleted, userState);
        }
        
        private void OnGetMetadataOperationCompleted(object arg) {
            if ((this.GetMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetadataCompleted(this, new GetMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PassportCookieValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hotmail.msn.com/ws/2004/09/oim/rsi/GetMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetMessageResponse", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
        public GetMessageResponseType GetMessage([System.Xml.Serialization.XmlElementAttribute("GetMessage", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")] GetMessageRequestType GetMessage1) {
            object[] results = this.Invoke("GetMessage", new object[] {
                        GetMessage1});
            return ((GetMessageResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageAsync(GetMessageRequestType GetMessage1) {
            this.GetMessageAsync(GetMessage1, null);
        }
        
        /// <remarks/>
        public void GetMessageAsync(GetMessageRequestType GetMessage1, object userState) {
            if ((this.GetMessageOperationCompleted == null)) {
                this.GetMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageOperationCompleted);
            }
            this.InvokeAsync("GetMessage", new object[] {
                        GetMessage1}, this.GetMessageOperationCompleted, userState);
        }
        
        private void OnGetMessageOperationCompleted(object arg) {
            if ((this.GetMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageCompleted(this, new GetMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PassportCookieValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hotmail.msn.com/ws/2004/09/oim/rsi/DeleteMessages", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteMessagesResponse", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
        public DeleteMessagesResponseType DeleteMessages([System.Xml.Serialization.XmlElementAttribute("DeleteMessages", Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")] DeleteMessagesRequestType DeleteMessages1) {
            object[] results = this.Invoke("DeleteMessages", new object[] {
                        DeleteMessages1});
            return ((DeleteMessagesResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessagesAsync(DeleteMessagesRequestType DeleteMessages1) {
            this.DeleteMessagesAsync(DeleteMessages1, null);
        }
        
        /// <remarks/>
        public void DeleteMessagesAsync(DeleteMessagesRequestType DeleteMessages1, object userState) {
            if ((this.DeleteMessagesOperationCompleted == null)) {
                this.DeleteMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessagesOperationCompleted);
            }
            this.InvokeAsync("DeleteMessages", new object[] {
                        DeleteMessages1}, this.DeleteMessagesOperationCompleted, userState);
        }
        
        private void OnDeleteMessagesOperationCompleted(object arg) {
            if ((this.DeleteMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessagesCompleted(this, new DeleteMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi", IsNullable=false)]
    public partial class PassportCookie : System.Web.Services.Protocols.SoapHeader {
        
        private string tField;
        
        private string pField;
        
        /// <remarks/>
        public string t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        public string p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class DeleteMessagesResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class DeleteMessagesRequestType {
        
        private string[] messageIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("messageId", IsNullable=false)]
        public string[] messageIds {
            get {
                return this.messageIdsField;
            }
            set {
                this.messageIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class GetMessageResponseType {
        
        private string getMessageResultField;
        
        /// <remarks/>
        public string GetMessageResult {
            get {
                return this.getMessageResultField;
            }
            set {
                this.getMessageResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class GetMessageRequestType {
        
        private string messageIdField;
        
        private bool alsoMarkAsReadField;
        
        /// <remarks/>
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public bool alsoMarkAsRead {
            get {
                return this.alsoMarkAsReadField;
            }
            set {
                this.alsoMarkAsReadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class GetMetadataResponseType {
        
        private MetaData mdField;
        
        /// <remarks/>
        public MetaData MD {
            get {
                return this.mdField;
            }
            set {
                this.mdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class MetaData {
        
        private MetadataMessage[] mField;
        
        private MetaDataQ qField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("M")]
        public MetadataMessage[] M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        public MetaDataQ Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class MetadataMessage {
        
        private string tField;
        
        private string sField;
        
        private System.DateTime rtField;
        
        private bool rtFieldSpecified;
        
        private bool rsField;
        
        private string szField;
        
        private string eField;
        
        private string iField;
        
        private string fField;
        
        private string nField;
        
        private string suField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RT {
            get {
                return this.rtField;
            }
            set {
                this.rtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RTSpecified {
            get {
                return this.rtFieldSpecified;
            }
            set {
                this.rtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RS {
            get {
                return this.rsField;
            }
            set {
                this.rsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SZ {
            get {
                return this.szField;
            }
            set {
                this.szField = value;
            }
        }
        
        /// <remarks/>
        public string E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        public string I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
            }
        }
        
        /// <remarks/>
        public string F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        public string SU {
            get {
                return this.suField;
            }
            set {
                this.suField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class MetaDataQ {
        
        private string qTMField;
        
        private string qNMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QTM {
            get {
                return this.qTMField;
            }
            set {
                this.qTMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string QNM {
            get {
                return this.qNMField;
            }
            set {
                this.qNMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotmail.msn.com/ws/2004/09/oim/rsi")]
    public partial class GetMetadataRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMetadataCompletedEventHandler(object sender, GetMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMessageCompletedEventHandler(object sender, GetMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMessageResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMessageResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteMessagesCompletedEventHandler(object sender, DeleteMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteMessagesResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteMessagesResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591